name: cs5228
channels:
  - conda-forge
  - defaults
dependencies:
  - black=22.6.0
  - ipykernel=6.15.0
  - ipython=8.10.0
  - jupyter_client=7.4.9
  - jupyter_core=5.2.0
  - kaggle=1.5.13
  - pandas=1.5.3
  - pip=22.3.1
  - python=3.10
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - setuptools=65.6.3
  - six=1.16.0
  - wheel=0.38.4
  - numpy=1.24.2
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - pytorch=1.13.1
  - tqdm=4.65.0
  - rasterio=1.3.6
  - elevation=1.1.3
  - geopandas=0.12.2
  - geopy=2.3.0
  - xgboost=1.7.4
  - pip:
      - opendatasets==0.1.22
